package hh.swd20.Bookstore.domain;

import java.util.List;

import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

//Book db autogenerated
@RepositoryRestResource
public interface BookRepository extends CrudRepository<Book, Long>{
	List<Book> findByTitle(@Param("title") String title); 
}
